# AQUÍ ESTÁ APLICADO EL PATRÓN API GATEWAY
spring.application.name=rednorte-bff
server.port=8080

# Enrutamiento hacia MS-Pacientes
spring.cloud.gateway.routes[0].id=ms-pacientes
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/pacientes/**

# Enrutamiento hacia MS-Citas
spring.cloud.gateway.routes[1].id=ms-citas
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/citas/**
