spring:
  application:
    name: rednorte-bff

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
